version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: meu-contador-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: meu_contador
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meu-contador-net

  redis:
    image: redis:alpine
    container_name: meu-contador-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - meu-contador-net

networks:
  meu-contador-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
